#ifndef _APPL_H_
#define _APPL_H_
#undef APPL_MAIN_APPLICATION_IDENTIFIER_PYTHON
#define APPL_MAIN_APPLICATION_IDENTIFIER_PYTHON 1
#if 0
export APPL_MAIN_APPLICATION_IDENTIFIER_PYTHON=1
#endif
#endif
