
#line 3 "lex.yy_.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer yy__create_buffer
#define yy_delete_buffer yy__delete_buffer
#define yy_flex_debug yy__flex_debug
#define yy_init_buffer yy__init_buffer
#define yy_flush_buffer yy__flush_buffer
#define yy_load_buffer_state yy__load_buffer_state
#define yy_switch_to_buffer yy__switch_to_buffer
#define yyin yy_in
#define yyleng yy_leng
#define yylex yy_lex
#define yylineno yy_lineno
#define yyout yy_out
#define yyrestart yy_restart
#define yytext yy_text
#define yywrap yy_wrap
#define yyalloc yy_alloc
#define yyrealloc yy_realloc
#define yyfree yy_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yy_restart(yy_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yy_leng;

extern FILE *yy_in, *yy_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yy_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yy_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yy_restart()), so that the user can continue scanning by
	 * just pointing yy_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yy_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yy_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yy_wrap()'s to do buffer switches
 * instead of setting up a fresh yy_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yy_restart (FILE *input_file  );
void yy__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy__create_buffer (FILE *file,int size  );
void yy__delete_buffer (YY_BUFFER_STATE b  );
void yy__flush_buffer (YY_BUFFER_STATE b  );
void yy_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void yy_pop_buffer_state (void );

static void yy_ensure_buffer_stack (void );
static void yy__load_buffer_state (void );
static void yy__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy__scan_bytes (yyconst char *bytes,int len  );

void *yy_alloc (yy_size_t  );
void *yy_realloc (void *,yy_size_t  );
void yy_free (void *  );

#define yy_new_buffer yy__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yy_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy__create_buffer(yy_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yy_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy__create_buffer(yy_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yy_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yy_in = (FILE *) 0, *yy_out = (FILE *) 0;

typedef int yy_state_type;

extern int yy_lineno;

int yy_lineno = 1;

extern char *yy_text;
#define yytext_ptr yy_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yy_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yy_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[232] =
    {   0,
        0,    0,    0,    0,   99,   98,   89,   12,   11,   11,
       89,   89,    8,   34,   37,   89,   10,   13,   26,   30,
       14,   29,   24,   33,    7,    7,   22,   77,   40,   28,
       41,   86,   88,   88,   88,   15,   89,   16,   38,   23,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   20,   39,   21,
       31,   12,    0,   11,   46,    0,    4,    0,    8,   57,
       61,    0,    3,    0,   27,   55,   53,   54,    0,    5,
       32,   56,    5,    7,    0,    0,    9,    6,    0,    7,
       35,   44,   45,   42,   43,   36,   88,    0,    0,   88,

       12,   62,   88,   73,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   19,   88,   18,   47,   88,   88,
       49,   88,   88,   88,   88,   88,   88,   88,   88,   63,
        4,    0,    3,    0,   58,   25,    0,    5,    7,   60,
       59,   50,   88,   88,   88,   88,   85,   65,   88,   88,
       88,   88,   88,   17,   88,   88,   88,   88,   48,   88,
       88,   88,   88,   81,   88,   88,   88,    0,    0,    0,
        0,    0,    0,   88,   88,   88,   88,   78,   79,   88,
       76,   88,   74,   88,   88,   88,   64,   88,   88,   88,
       88,   84,   88,    0,    0,    0,    0,    0,    0,   88,

       70,   87,   88,   88,   88,   88,   88,   88,   66,   69,
       88,   80,   68,    0,    2,    0,    0,    1,    0,   52,
       88,   82,   88,   75,   72,   51,   67,   88,   83,   71,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,    1,   27,   28,   28,   28,   28,   29,   28,
       30,   30,   30,   31,   30,   32,   30,   30,   30,   30,
       30,   33,   30,   30,   34,   30,   30,   35,   30,   30,
       36,   37,   38,   39,   30,   40,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   31,   50,   51,   52,   53,
       54,   55,   30,   56,   57,   58,   59,   30,   60,   61,
       62,   30,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    4,    4,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[244] =
    {   0,
        0,    0,    0,    0,  376,  377,  377,   65,  377,  372,
      349,   62,    0,  348,  347,   59,  377,  377,   57,  346,
      377,  345,   54,   54,   86,   69,  377,  377,   52,  344,
       55,  377,    0,   77,  102,  377,   81,  377,  343,  377,
       38,  311,   43,  321,   58,   73,  314,   86,  323,  309,
      306,   69,  118,  305,  120,   44,  311,  377,  334,  377,
      377,  109,  130,  377,  377,  107,  352,  354,    0,  377,
      377,  113,  346,  352,  329,  377,  377,  377,  336,  135,
      377,  377,  141,  158,  175,  191,  377,  377,    0,  196,
      327,  377,  377,  377,  377,  326,    0,  130,  131,  139,

      171,  377,  306,  292,  303,  306,  293,  106,   91,  126,
      292,  288,  289,  288,    0,  286,    0,    0,  288,  281,
        0,  281,  288,  287,  277,  272,  284,  274,  286,  377,
      377,  145,  377,  181,  377,  377,  164,  202,  149,  377,
      377,    0,  285,  288,  271,  269,    0,    0,  280,  280,
      279,  280,  281,    0,  269,  278,  265,  276,    0,  225,
      225,  220,  213,    0,  213,  215,  210,  182,  187,    0,
      189,  192,    0,  204,  209,  199,  206,    0,    0,  199,
        0,  202,    0,  211,  195,  206,    0,  191,  203,  190,
      199,    0,  199,  195,  208,    0,  220,  221,    0,  184,

        0,    0,  187,  181,  187,  186,  178,  157,    0,    0,
      144,    0,    0,  228,  377,    0,  225,  377,    0,    0,
      106,    0,   80,    0,    0,    0,    0,   71,    0,    0,
      377,  265,  270,  275,  280,  282,  100,  287,  292,  297,
      302,  307,  312
    } ;

static yyconst flex_int16_t yy_def[244] =
    {   0,
      232,  232,  231,    3,  231,  231,  231,  231,  231,  231,
      231,  233,  234,  231,  231,  235,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  236,  236,  236,  231,  231,  231,  231,  231,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  231,  231,  231,
      231,  231,  231,  231,  231,  233,  231,  233,  234,  231,
      231,  235,  231,  235,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  237,  231,
      231,  231,  231,  231,  231,  231,  236,  233,  235,  236,

      231,  231,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  231,
      231,  238,  231,  239,  231,  231,  231,  231,  237,  231,
      231,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  238,  240,  238,
      239,  241,  239,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  238,  242,  240,  239,  243,  241,  236,

      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  238,  231,  242,  239,  231,  243,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
        0,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231
    } ;

static yyconst flex_int16_t yy_nxt[444] =
    {   0,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       26,   27,   28,   29,   30,   31,   32,   33,   33,   33,
       33,   33,   34,   35,   33,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   33,   48,   33,
       49,   33,   50,   51,   52,   53,   33,   54,   55,   56,
       33,   57,   58,   59,   60,   61,   62,   67,   73,   75,
       79,   81,   80,   80,   80,   91,   92,   93,   82,   95,
       96,   76,   98,   62,  101,   83,   99,   90,   90,   90,
      103,  127,  128,  106,  104,   74,  107,   86,   68,   87,

       88,   63,   83,  139,   84,   84,   85,   98,  109,  122,
       62,   99,  131,   86,   86,  230,   87,   88,  110,   88,
       89,  111,  133,   98,  123,   98,  112,   99,  113,   99,
       86,  115,   62,  101,  100,   67,   88,  116,  117,  149,
       73,  229,  118,   68,   98,   63,   89,  150,   99,   74,
      169,  147,  100,   80,   80,   80,  148,  100,  124,   80,
       80,   80,  125,   86,  228,   87,   68,   74,  151,   86,
      152,   87,   62,   62,   83,  100,   84,   84,   85,   86,
       88,  170,  138,  138,  138,   86,   86,  169,   87,   88,
      172,   83,  195,   85,   85,   85,  227,  226,  172,   88,

      169,  198,   86,   86,  137,   87,  137,   63,   88,  138,
      138,  138,   83,  215,   90,   90,   90,  173,  170,   86,
      138,  138,  138,  196,   86,  173,   87,   88,  199,  172,
      218,  170,   87,  169,  172,  225,  224,  223,  222,  221,
       86,  220,  213,  212,  216,  211,   88,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  173,  219,  201,  200,
      193,  173,  192,  191,  170,    6,    6,    6,    6,    6,
       66,  190,   66,   66,   66,   69,  189,  188,   69,   69,
       72,  187,   72,   72,   72,   97,   97,  168,  168,  168,
      168,  168,  171,  171,  171,  171,  171,  194,  194,  194,

      194,  194,  197,  197,  197,  197,  197,  214,  214,  214,
      214,  214,  217,  217,  217,  217,  217,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  146,  145,  144,  143,  142,
      141,  140,  136,  135,   72,  134,   66,  132,  130,  129,
      126,  121,  120,  119,  114,  108,  105,  102,   94,   78,
       77,   71,   70,   65,   64,  231,    5,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231
    } ;

static yyconst flex_int16_t yy_chk[444] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    8,   12,   16,   19,
       23,   24,   23,   23,   23,   29,   29,   29,   24,   31,
       31,   19,   34,   37,   37,   26,   34,   26,   26,   26,
       41,   56,   56,   43,   41,   16,   43,   26,   12,   26,

       26,    8,   25,  237,   25,   25,   25,   35,   45,   52,
       62,   35,   66,   26,   25,  228,   25,   25,   45,   26,
       25,   46,   72,   53,   52,   55,   46,   53,   46,   55,
       25,   48,   63,   63,   35,   98,   25,   48,   48,  109,
       99,  223,   48,   66,  100,   62,   25,  109,  100,   72,
      132,  108,   55,   80,   80,   80,  108,   35,   53,   83,
       83,   83,   53,   80,  221,   80,   98,   99,  110,   83,
      110,   83,  101,  101,   84,   55,   84,   84,   84,   80,
      139,  132,  137,  137,  137,   83,   84,  168,   84,   84,
      134,   85,  169,   85,   85,   85,  211,  208,  171,  139,

      194,  172,   84,   85,   86,   85,   86,  101,   84,   86,
       86,   86,   90,  195,   90,   90,   90,  134,  168,   85,
      138,  138,  138,  169,   90,  171,   90,   90,  172,  197,
      198,  194,  138,  214,  217,  207,  206,  205,  204,  203,
       90,  200,  193,  191,  195,  190,   90,  189,  188,  186,
      185,  184,  182,  180,  177,  176,  197,  198,  175,  174,
      167,  217,  166,  165,  214,  232,  232,  232,  232,  232,
      233,  163,  233,  233,  233,  234,  162,  161,  234,  234,
      235,  160,  235,  235,  235,  236,  236,  238,  238,  238,
      238,  238,  239,  239,  239,  239,  239,  240,  240,  240,

      240,  240,  241,  241,  241,  241,  241,  242,  242,  242,
      242,  242,  243,  243,  243,  243,  243,  158,  157,  156,
      155,  153,  152,  151,  150,  149,  146,  145,  144,  143,
      129,  128,  127,  126,  125,  124,  123,  122,  120,  119,
      116,  114,  113,  112,  111,  107,  106,  105,  104,  103,
       96,   91,   79,   75,   74,   73,   68,   67,   59,   57,
       54,   51,   50,   49,   47,   44,   42,   39,   30,   22,
       20,   15,   14,   11,   10,    5,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy__flex_debug;
int yy__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yy_text;
#line 1 "x_rm1.lex"
/*BEGIN decl DELIMITER*/

#line 5 "x_rm1.lex"
int mainscannerstate=1;

/*END decl DELIMITER*/
#line 14 "x_rm1.lex"
#include "x_io1.h"
#ifndef FLEX_BEGIN_NEXT_TOKEN
#define FLEX_BEGIN_NEXT_TOKEN
#else
static parser_master_t* mp=NULL;
//#define change_state (mp->change_state)
//#define change_pos (mp->change_pos)
//#define current_text_heap (mp->current_text_heap)
#endif
#line 27 "x_rm1.lex"
FLEX_DECLARATIONS
/* %% has to be on the beginning of the line !!!*/
#line 669 "lex.yy_.c"

#define INITIAL 0
#define MAINSCANNERSTATE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yy_lex_destroy (void );

int yy_get_debug (void );

void yy_set_debug (int debug_flag  );

YY_EXTRA_TYPE yy_get_extra (void );

void yy_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *yy_get_in (void );

void yy_set_in  (FILE * in_str  );

FILE *yy_get_out (void );

void yy_set_out  (FILE * out_str  );

int yy_get_leng (void );

char *yy_get_text (void );

int yy_get_lineno (void );

void yy_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yy_wrap (void );
#else
extern int yy_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yy_text, yy_leng, 1, yy_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yy_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yy_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yy_in))==0 && ferror(yy_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yy_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yy_lex (void);

#define YY_DECL int yy_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yy_text and yy_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 33 "x_rm1.lex"



    if(MAINSCANNERSTATE!=1){printf("new version of flax has changed states numbering for MAINSCANNERSTATE");exit(1);}



	 FLEX_BEGIN(MAINSCANNERSTATE)
#line 861 "lex.yy_.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yy_in )
			yy_in = stdin;

		if ( ! yy_out )
			yy_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yy_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy__create_buffer(yy_in,YY_BUF_SIZE );
		}

		yy__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yy_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 232 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 377 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case YY_STATE_EOF(MAINSCANNERSTATE):
#line 41 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_EXIT);FLEX_INCREASE_POSITION;return TOK_EXIT;

	YY_BREAK
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 44 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_LONGSTRINGLITERALSINGLEQUOTE);FLEX_INCREASE_POSITION;return TOK_LONGSTRINGLITERALSINGLEQUOTE;

	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 47 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_LONGSTRINGLITERALDOUBLEQUOTE);FLEX_INCREASE_POSITION;return TOK_LONGSTRINGLITERALDOUBLEQUOTE;

	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 50 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_SHORTSTRINGLITERALSINGLEQUOTE);FLEX_INCREASE_POSITION;return TOK_SHORTSTRINGLITERALSINGLEQUOTE;

	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 53 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_SHORTSTRINGLITERALDOUBLEQUOTE);FLEX_INCREASE_POSITION;return TOK_SHORTSTRINGLITERALDOUBLEQUOTE;

	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_FLOATNUMBER);FLEX_INCREASE_POSITION;return TOK_FLOATNUMBER;

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 59 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_LONGINTEGER);FLEX_INCREASE_POSITION;return TOK_LONGINTEGER;

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 62 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_INTEGER);FLEX_INCREASE_POSITION;return TOK_INTEGER;

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_COMMENT);FLEX_INCREASE_POSITION;return TOK_COMMENT;

	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_IMAGNUMBER);FLEX_INCREASE_POSITION;return TOK_IMAGNUMBER;

	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_OP);FLEX_INCREASE_POSITION;return TOK_OP;

	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 74 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_NEWLINE);FLEX_INCREASE_POSITION;return TOK_NEWLINE;

	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 77 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_SPACE);FLEX_INCREASE_POSITION;return TOK_SPACE;

	YY_BREAK
case 13:
YY_RULE_SETUP
#line 80 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_CP);FLEX_INCREASE_POSITION;return TOK_CP;

	YY_BREAK
case 14:
YY_RULE_SETUP
#line 83 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_COMMA);FLEX_INCREASE_POSITION;return TOK_COMMA;

	YY_BREAK
case 15:
YY_RULE_SETUP
#line 86 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_OB);FLEX_INCREASE_POSITION;return TOK_OB;

	YY_BREAK
case 16:
YY_RULE_SETUP
#line 89 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_CB);FLEX_INCREASE_POSITION;return TOK_CB;

	YY_BREAK
case 17:
YY_RULE_SETUP
#line 92 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_FOR);FLEX_INCREASE_POSITION;return TOK_FOR;

	YY_BREAK
case 18:
YY_RULE_SETUP
#line 95 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_IN);FLEX_INCREASE_POSITION;return TOK_IN;

	YY_BREAK
case 19:
YY_RULE_SETUP
#line 98 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_IF);FLEX_INCREASE_POSITION;return TOK_IF;

	YY_BREAK
case 20:
YY_RULE_SETUP
#line 101 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_AO);FLEX_INCREASE_POSITION;return TOK_AO;

	YY_BREAK
case 21:
YY_RULE_SETUP
#line 104 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_AC);FLEX_INCREASE_POSITION;return TOK_AC;

	YY_BREAK
case 22:
YY_RULE_SETUP
#line 107 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_CO);FLEX_INCREASE_POSITION;return TOK_CO;

	YY_BREAK
case 23:
YY_RULE_SETUP
#line 110 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_BQ);FLEX_INCREASE_POSITION;return TOK_BQ;

	YY_BREAK
case 24:
YY_RULE_SETUP
#line 113 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_FS);FLEX_INCREASE_POSITION;return TOK_FS;

	YY_BREAK
case 25:
YY_RULE_SETUP
#line 116 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_FSFSFS);FLEX_INCREASE_POSITION;return TOK_FSFSFS;

	YY_BREAK
case 26:
YY_RULE_SETUP
#line 119 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_ST);FLEX_INCREASE_POSITION;return TOK_ST;

	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_STST);FLEX_INCREASE_POSITION;return TOK_STST;

	YY_BREAK
case 28:
YY_RULE_SETUP
#line 125 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_EQ);FLEX_INCREASE_POSITION;return TOK_EQ;

	YY_BREAK
case 29:
YY_RULE_SETUP
#line 128 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_MN);FLEX_INCREASE_POSITION;return TOK_MN;

	YY_BREAK
case 30:
YY_RULE_SETUP
#line 131 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_PL);FLEX_INCREASE_POSITION;return TOK_PL;

	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_TL);FLEX_INCREASE_POSITION;return TOK_TL;

	YY_BREAK
case 32:
YY_RULE_SETUP
#line 137 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_DIDI);FLEX_INCREASE_POSITION;return TOK_DIDI;

	YY_BREAK
case 33:
YY_RULE_SETUP
#line 140 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_DI);FLEX_INCREASE_POSITION;return TOK_DI;

	YY_BREAK
case 34:
YY_RULE_SETUP
#line 143 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_PC);FLEX_INCREASE_POSITION;return TOK_PC;

	YY_BREAK
case 35:
YY_RULE_SETUP
#line 146 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_LTLT);FLEX_INCREASE_POSITION;return TOK_LTLT;

	YY_BREAK
case 36:
YY_RULE_SETUP
#line 149 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_GTGT);FLEX_INCREASE_POSITION;return TOK_GTGT;

	YY_BREAK
case 37:
YY_RULE_SETUP
#line 152 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_AS);FLEX_INCREASE_POSITION;return TOK_AS;

	YY_BREAK
case 38:
YY_RULE_SETUP
#line 155 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_EX);FLEX_INCREASE_POSITION;return TOK_EX;

	YY_BREAK
case 39:
YY_RULE_SETUP
#line 158 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_OR);FLEX_INCREASE_POSITION;return TOK_OR;

	YY_BREAK
case 40:
YY_RULE_SETUP
#line 161 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_LT);FLEX_INCREASE_POSITION;return TOK_LT;

	YY_BREAK
case 41:
YY_RULE_SETUP
#line 164 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_GT);FLEX_INCREASE_POSITION;return TOK_GT;

	YY_BREAK
case 42:
YY_RULE_SETUP
#line 167 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_EQEQ);FLEX_INCREASE_POSITION;return TOK_EQEQ;

	YY_BREAK
case 43:
YY_RULE_SETUP
#line 170 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_GTEQ);FLEX_INCREASE_POSITION;return TOK_GTEQ;

	YY_BREAK
case 44:
YY_RULE_SETUP
#line 173 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_LTEQ);FLEX_INCREASE_POSITION;return TOK_LTEQ;

	YY_BREAK
case 45:
YY_RULE_SETUP
#line 176 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_LTGT);FLEX_INCREASE_POSITION;return TOK_LTGT;

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 179 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_ETEQ);FLEX_INCREASE_POSITION;return TOK_ETEQ;

	YY_BREAK
case 47:
YY_RULE_SETUP
#line 182 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_IS);FLEX_INCREASE_POSITION;return TOK_IS;

	YY_BREAK
case 48:
YY_RULE_SETUP
#line 185 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_NOT);FLEX_INCREASE_POSITION;return TOK_NOT;

	YY_BREAK
case 49:
YY_RULE_SETUP
#line 188 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_WRITTEN_OR);FLEX_INCREASE_POSITION;return TOK_WRITTEN_OR;

	YY_BREAK
case 50:
YY_RULE_SETUP
#line 191 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_AND);FLEX_INCREASE_POSITION;return TOK_AND;

	YY_BREAK
case 51:
YY_RULE_SETUP
#line 194 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_LAMBDA);FLEX_INCREASE_POSITION;return TOK_LAMBDA;

	YY_BREAK
case 52:
YY_RULE_SETUP
#line 197 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_ASSERT);FLEX_INCREASE_POSITION;return TOK_ASSERT;

	YY_BREAK
case 53:
YY_RULE_SETUP
#line 200 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_PLEQ);FLEX_INCREASE_POSITION;return TOK_PLEQ;

	YY_BREAK
case 54:
YY_RULE_SETUP
#line 203 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_MNEQ);FLEX_INCREASE_POSITION;return TOK_MNEQ;

	YY_BREAK
case 55:
YY_RULE_SETUP
#line 206 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_STEQ);FLEX_INCREASE_POSITION;return TOK_STEQ;

	YY_BREAK
case 56:
YY_RULE_SETUP
#line 209 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_DIEQ);FLEX_INCREASE_POSITION;return TOK_DIEQ;

	YY_BREAK
case 57:
YY_RULE_SETUP
#line 212 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_PCEQ);FLEX_INCREASE_POSITION;return TOK_PCEQ;

	YY_BREAK
case 58:
YY_RULE_SETUP
#line 215 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_STSTEQ);FLEX_INCREASE_POSITION;return TOK_STSTEQ;

	YY_BREAK
case 59:
YY_RULE_SETUP
#line 218 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_GTGTEQ);FLEX_INCREASE_POSITION;return TOK_GTGTEQ;

	YY_BREAK
case 60:
YY_RULE_SETUP
#line 221 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_LTLTEQ);FLEX_INCREASE_POSITION;return TOK_LTLTEQ;

	YY_BREAK
case 61:
YY_RULE_SETUP
#line 224 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_ASEQ);FLEX_INCREASE_POSITION;return TOK_ASEQ;

	YY_BREAK
case 62:
YY_RULE_SETUP
#line 227 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_EXEQ);FLEX_INCREASE_POSITION;return TOK_EXEQ;

	YY_BREAK
case 63:
YY_RULE_SETUP
#line 230 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_OREQ);FLEX_INCREASE_POSITION;return TOK_OREQ;

	YY_BREAK
case 64:
YY_RULE_SETUP
#line 233 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_PASS);FLEX_INCREASE_POSITION;return TOK_PASS;

	YY_BREAK
case 65:
YY_RULE_SETUP
#line 236 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_DEL);FLEX_INCREASE_POSITION;return TOK_DEL;

	YY_BREAK
case 66:
YY_RULE_SETUP
#line 239 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_PRINT);FLEX_INCREASE_POSITION;return TOK_PRINT;

	YY_BREAK
case 67:
YY_RULE_SETUP
#line 242 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_RETURN);FLEX_INCREASE_POSITION;return TOK_RETURN;

	YY_BREAK
case 68:
YY_RULE_SETUP
#line 245 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_YIELD);FLEX_INCREASE_POSITION;return TOK_YIELD;

	YY_BREAK
case 69:
YY_RULE_SETUP
#line 248 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_RAISE);FLEX_INCREASE_POSITION;return TOK_RAISE;

	YY_BREAK
case 70:
YY_RULE_SETUP
#line 251 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_BREAK);FLEX_INCREASE_POSITION;return TOK_BREAK;

	YY_BREAK
case 71:
YY_RULE_SETUP
#line 254 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_CONTINUE);FLEX_INCREASE_POSITION;return TOK_CONTINUE;

	YY_BREAK
case 72:
YY_RULE_SETUP
#line 257 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_IMPORT);FLEX_INCREASE_POSITION;return TOK_IMPORT;

	YY_BREAK
case 73:
YY_RULE_SETUP
#line 260 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_WRITTEN_AS);FLEX_INCREASE_POSITION;return TOK_WRITTEN_AS;

	YY_BREAK
case 74:
YY_RULE_SETUP
#line 263 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_FROM);FLEX_INCREASE_POSITION;return TOK_FROM;

	YY_BREAK
case 75:
YY_RULE_SETUP
#line 266 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_GLOBAL);FLEX_INCREASE_POSITION;return TOK_GLOBAL;

	YY_BREAK
case 76:
YY_RULE_SETUP
#line 269 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_EXEC);FLEX_INCREASE_POSITION;return TOK_EXEC;

	YY_BREAK
case 77:
YY_RULE_SETUP
#line 272 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_SC);FLEX_INCREASE_POSITION;return TOK_SC;

	YY_BREAK
case 78:
YY_RULE_SETUP
#line 275 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_ELIF);FLEX_INCREASE_POSITION;return TOK_ELIF;

	YY_BREAK
case 79:
YY_RULE_SETUP
#line 278 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_ELSE);FLEX_INCREASE_POSITION;return TOK_ELSE;

	YY_BREAK
case 80:
YY_RULE_SETUP
#line 281 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_WHILE);FLEX_INCREASE_POSITION;return TOK_WHILE;

	YY_BREAK
case 81:
YY_RULE_SETUP
#line 284 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_TRY);FLEX_INCREASE_POSITION;return TOK_TRY;

	YY_BREAK
case 82:
YY_RULE_SETUP
#line 287 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_EXCEPT);FLEX_INCREASE_POSITION;return TOK_EXCEPT;

	YY_BREAK
case 83:
YY_RULE_SETUP
#line 290 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_FINALLY);FLEX_INCREASE_POSITION;return TOK_FINALLY;

	YY_BREAK
case 84:
YY_RULE_SETUP
#line 293 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_WITH);FLEX_INCREASE_POSITION;return TOK_WITH;

	YY_BREAK
case 85:
YY_RULE_SETUP
#line 296 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_DEF);FLEX_INCREASE_POSITION;return TOK_DEF;

	YY_BREAK
case 86:
YY_RULE_SETUP
#line 299 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_STRUDL);FLEX_INCREASE_POSITION;return TOK_STRUDL;

	YY_BREAK
case 87:
YY_RULE_SETUP
#line 302 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_CLASS);FLEX_INCREASE_POSITION;return TOK_CLASS;

	YY_BREAK
case 88:
YY_RULE_SETUP
#line 305 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_IDENTIFIER);FLEX_INCREASE_POSITION;return TOK_IDENTIFIER;

	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 308 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_ANYCHAR);FLEX_INCREASE_POSITION;return TOK_ANYCHAR;

	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 311 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_INDENT);FLEX_INCREASE_POSITION;return TOK_INDENT;

	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 314 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_DEDENT);FLEX_INCREASE_POSITION;return TOK_DEDENT;

	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 317 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_SPACE_INDENT);FLEX_INCREASE_POSITION;return TOK_SPACE_INDENT;

	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 320 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_SPACE_EMPTY_LINE);FLEX_INCREASE_POSITION;return TOK_SPACE_EMPTY_LINE;

	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 323 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_SPACE_NO_INDENT);FLEX_INCREASE_POSITION;return TOK_SPACE_NO_INDENT;

	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 326 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_NEW_LINE_IGNORED);FLEX_INCREASE_POSITION;return TOK_NEW_LINE_IGNORED;

	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 329 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_SPACE_AT_END_OF_LINE);FLEX_INCREASE_POSITION;return TOK_SPACE_AT_END_OF_LINE;

	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 332 "x_rm1.lex"

FLEX_NEW_TERMINAL(TOK_SPACE_OTHER);FLEX_INCREASE_POSITION;return TOK_SPACE_OTHER;

	YY_BREAK
case 98:
YY_RULE_SETUP
#line 336 "x_rm1.lex"
ECHO;
	YY_BREAK
#line 1649 "lex.yy_.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yy_in at a new source and called
			 * yy_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yy_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yy_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yy_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yy_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yy_restart(yy_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yy_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 232 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 232 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 231);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yy_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yy_restart(yy_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yy_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yy_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yy_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yy_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy__create_buffer(yy_in,YY_BUF_SIZE );
	}

	yy__init_buffer(YY_CURRENT_BUFFER,input_file );
	yy__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yy_pop_buffer_state();
	 *		yy_push_buffer_state(new_buffer);
     */
	yy_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yy_wrap()) processing, but the only time this flag
	 * is looked at is after yy_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yy_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yy_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy__create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy__create_buffer()
 * 
 */
    void yy__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_free((void *) b->yy_ch_buf  );

	yy_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yy_restart() or at EOF.
 */
    static void yy__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy__init_buffer was _probably_
     * called from yy_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yy_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yy_ensure_buffer_stack();

	/* This block is copied from yy__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy__switch_to_buffer. */
	yy__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yy_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yy_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yy_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yy_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yy_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yy_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yy_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy__scan_bytes() instead.
 */
YY_BUFFER_STATE yy__scan_string (yyconst char * yystr )
{
    
	return yy__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yy_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yy_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yy_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yy_text[yy_leng] = (yy_hold_char); \
		(yy_c_buf_p) = yy_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yy_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yy_get_lineno  (void)
{
        
    return yy_lineno;
}

/** Get the input stream.
 * 
 */
FILE *yy_get_in  (void)
{
        return yy_in;
}

/** Get the output stream.
 * 
 */
FILE *yy_get_out  (void)
{
        return yy_out;
}

/** Get the length of the current token.
 * 
 */
int yy_get_leng  (void)
{
        return yy_leng;
}

/** Get the current token.
 * 
 */

char *yy_get_text  (void)
{
        return yy_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yy_set_lineno (int  line_number )
{
    
    yy_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy__switch_to_buffer
 */
void yy_set_in (FILE *  in_str )
{
        yy_in = in_str ;
}

void yy_set_out (FILE *  out_str )
{
        yy_out = out_str ;
}

int yy_get_debug  (void)
{
        return yy__flex_debug;
}

void yy_set_debug (int  bdebug )
{
        yy__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yy_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yy_in = stdin;
    yy_out = stdout;
#else
    yy_in = (FILE *) 0;
    yy_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yy_lex_init()
     */
    return 0;
}

/* yy_lex_destroy is for both reentrant and non-reentrant scanners. */
int yy_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yy_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	yy_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yy_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yy_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yy_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yy_free (void * ptr )
{
	free( (char *) ptr );	/* see yy_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 336 "x_rm1.lex"




